### ISSUE TITLE
OneDrive automatically unmounts after several hours 

### ISSUE THREAD

**Issue by calvinturbo** [rooey/chromeos-filesystem-onedrive#10]
It says my token has expired after a few hours.

**Comment by yoichiro** [comment]
@calvinturbo This is because the Microsoft OAuth2 specification. In this application, OAuth2 Implicit grant is used to get the access token to use each API of the OneDrive. The access token will be expired in the several hours after issued. Also, the refresh token cannot be issued in the case of using the Implicit grant. Thus, I think that I cannot solve this issue. I want to decide that this is a specification for this application. Sorry.

**Comment by rooey** [comment]
#13 duplicate
