### ISSUE TITLE
Mounting Seems to Freeze File App and I get constant token timeout messages.

### ISSUE THREAD

**Issue by jfinn1319** [rooey/chromeos-filesystem-onedrive#14]

**Comment by rooey** [comment]
I have spent some time debugging this; it's caused by a file stored on your OneDrive.

The OneDrive app can't cope with "section" files. (Typically OneNote notebooks).

I've tried to fix the issue but as it's using an older app framework, I can't get past authentication :)

app/scripts/onedrive_client.js - line 500:
500                 entryMetadata.mimeType = content.file.mimeType;

We need a check prior to this for Section files; or a sanity check on content.file.mimeType prior.
