### ISSUE TITLE
Everything is broken.

### ISSUE THREAD

**Issue by FrozenPigs** [rooey/chromeos-filesystem-onedrive#19]
Pls fix.

**Comment by rooey** [comment]
Can you be more specific as to what your issue is?

**Comment by FrozenPigs** [comment]
Can't log on with the OneDrive account given by my college, presumably it wont work with OneDrive for business but I got no idea. Also if you want more issues there are a lot of people complaining in the reviews on the web store.

**Comment by rooey** [comment]
The current release does not support OneDrive for business or education.

I've only recently started working on the project, and am working on a few remaining snags.  This, and a few of the other troublesome issues have been fixed in the current development build.

I hope to get a release out into the wild real soon.
Stay tuned :)

**Comment by FrozenPigs** [comment]
Chill g, I'll keep an eye on your repo, I'd like a copy of this that works with OneDrive for education because it would help with my college work.

**Comment by rooey** [comment]
If you're interested in testing out the current build; drop me a note.
